baseURL = "http://unknownapedia.com/"
languageCode = "en-us"
title = "Unknownapedia"

disableHugoGeneratorInject = true
disableKinds = ["RSS"]

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true
